version = 1
SPDX-PackageName = "CryptPad Server"
SPDX-PackageSupplier = "XWiki CryptPad Team <contact@cryptpad.org>"
SPDX-PackageDownloadLocation = "https://cryptpad.org"

[[annotations]]
path = "**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 XWiki CryptPad Team <contact@cryptpad.org> and contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
